export const STEPS = [
  "WELCOME",
  "LANGUAGES",
  "MICROPHONE",
  "NOTIFICATIONS",
  "OVERLAY",
  "ACCESSIBILITY",
  "API_KEYS",
  "FINISH",
] as const

export const ANDROID_NOTIFICATION_VERSION = 33
export const BACK_BUTTON_WIDTH = 80
export const API_KEY_SECTION_MARGIN_TOP = 24
